name: multipick
description: Flutter multipick lets you select easy things which are related.
version: 0.0.1
homepage: https://www.ud-softworks.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
